display_name: Re
package_name: re

maintainer:
  name: Michael Christenson II
  email: m3talsmith@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:

essential: false

icon: linux/assets/re.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Resume
  - Resume Manager

generic_name: Re

categories:
  - Development
  - Utility

startup_notify: true
